[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.28"
evm_version = "cancun"

[fuzz]
runs = 10000
max_test_rejects = 65536
seed = '0x1'

[invariant]
runs = 256
depth = 50
fail_on_revert = false
call_override = false
dictionary_weight = 80

optimizer = true
optimizer_runs = 200
via_ir = false

gas_limit = 30000000
gas_price = 0

verbosity = 3
